# Generated by Django 4.1.3 on 2022-11-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guineapig',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
