# Generated by Django 4.1.3 on 2022-11-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feeding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('H', 'Hay'), ('P', 'Pellets'), ('L', 'Lettuce'), ('B', 'Bell Pepper'), ('A', 'Apples'), ('O', 'Oranges')], default='H', max_length=1),
        ),
    ]
