# Generated by Django 4.1.3 on 2022-11-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='guineapig',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
